source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXSafeTransition_Example', :exclusive => true do
  pod "BXSafeTransition", :path => "../"
end

target 'BXSafeTransition_Tests', :exclusive => true do
  pod "BXSafeTransition", :path => "../"

  
end
